[package]
name = "safe-txe-circuit"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
aes-gcm = { version = "0.10", default-features = false, features = ["aes"] }
aes-kw = "0.2"
curve25519-dalek = "4"
sha2 = "0.10"
sha3 = "0.10"
